version: "3.9"

services:
  portfolio:
    build: .
    container_name: astro-portfolio
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`www.rubio-abela.fr`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=le"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
